### ISSUE TITLE
Can't update custom messages on verify action

### ISSUE THREAD

**Issue by nandordudas** [adonisjs/adonis-persona#28]
Is an issue? If i try to login with email of a non existing user, the `uid.exists` key is not exists under `verify`, but it does under `undefined` key.

[./src/Persona.js@449](https://github.com/adonisjs/adonis-persona/blob/develop/src/Persona.js#L449)
[./src/Persona.js@135](https://github.com/adonisjs/adonis-persona/blob/develop/src/Persona.js#L135)

`./config/persona.js`
```js
module.exports = {
  validationMessages (action) {
    switch (action) {
      case 'passwordUpdate':
        return {
          'old_password.mis_match': '>>>Doesnt work<<<'
        }
      case 'verify':
        return {
          'uid.exists': '>>>Doesnt work<<<',
          'password.mis_match': '>>>Doesnt works<<<'
        }
      case undefined:
        return {
          'uid.exists': '>>>It works<<<',
          'old_password.mis_match': '>>>It works<<<',
          'password.mis_match': '>>>It works<<<'
        }
      default:
        return {}
    }
}
```
`./app/Controllers/Http/AuthController.js`
```js
class AuthController {
  async login ({ request, response, auth }) {
    Persona.loginRules = () => ({
      uid: 'required|email',
      password: 'required'
    })
    const payload = request.only(['uid', 'password'])
    try {
      const user = await Persona.verify(payload)
      await auth.login(user)
    } catch (error) {
      return response.send({ error })
    }
  }
}
```

node: v11.7.0, npm: 6.6.0, Adonis: 4.1.0

**Comment by nandordudas** [comment]
![tempsnip](https://user-images.githubusercontent.com/15153245/51679076-3726c800-1fde-11e9-932f-9c69c3c2d0e9.png)

**Comment by RomainLanz** [comment]
Hey @nandordudas! 👋 

I didn't understand your issue, could you please try to rephrase it?

**Comment by RomainLanz** [comment]
Hey @nandordudas! 👋 

Your code should work. Could you please create a repository with the minimum amount of code to reproduce the issue?

**Comment by nandordudas** [comment]
Hi @RomainLanz!

Of cource, [here](https://github.com/nandordudas/adonis-persona-custom-message#test-malfunction) you are!

**Comment by nandordudas** [comment]
![image](https://user-images.githubusercontent.com/15153245/52475395-a6ceb280-2b9b-11e9-82f3-13bf296778f3.png)

**Comment by emanuel15** [comment]
I had this same issue today. The problem is that the `runValidation` (the function that actually calls the action "verify") inside verify [(L518)](https://github.com/adonisjs/adonis-persona/blob/develop/src/Persona.js#L518) is not failing because `verify` passes the `loginRules()` which are:
```javascript
loginRules () {
  return {
    'uid': 'required',
    [this.config.password]: 'required'
  }
}
```
so the validation passes if you provide a valid uid and password, even if they don't exist in the database, thus [this condition](https://github.com/adonisjs/adonis-persona/blob/develop/src/Persona.js#L391) never evaluates to true
then when [getUserByUids](https://github.com/adonisjs/adonis-persona/blob/develop/src/Persona.js#L519) get called, it fails and throws an exception using the [_makeCustomMessage](https://github.com/adonisjs/adonis-persona/blob/develop/src/Persona.js#L449), but this method doesn't pass any action to [getMessages](https://github.com/adonisjs/adonis-persona/blob/develop/src/Persona.js#L136), so that's why the 'verify' action doesn't work the way it should
